TeamRocket#3: Pipeline Refinement
cse112-sp22-group3/rocketrecipes pull request #5
Opened 2022-04-26 00:06 UTC by TacoTuesdayX

This pull request is primarily for pipeline refinement, under `.github/workflows/`. I went with the naming convention:

[Team Name]#[ticket number]: ticket title
for pull request title, and
[Team Name]-[appropriate]-[branch]-[title] 
for the branch name.

and anything not related to a ticket:

NO TICKET: (name of quick fix)
NO-TICKET-(name)-(of)-(quick)-(fix)

Can change conventions later

2022-04-26 00:12 UTC, TacoTuesdayX commented on .github/workflows/jsdocs-main.yml
> +    branches: [ main ]
redundant changes, intended only to trigger the pipeline with a fresh pull request.

2022-04-28 05:37 UTC, gmihir requested changes
Please bring back line 38 in jsdocs-pr.yml. This line creates a branch with the documentation for the PR and should not be deleted. Deleting it defeats the purpose of the workflow.

2022-05-02 00:38 UTC, gmihir approved these changes

2022-05-02 22:42 UTC, williamcsimpson approved these changes
Seems like minor changes; I don't see anything egregious.

2022-05-02 22:52 UTC, merged