Syncing Users between database and
cse112-sp22-group3/rocketrecipes pull request #66
Opened 2022-05-28 01:26 UTC by DanlandYZ

modifies getAllRecipes (probably need further modifications) 
user can add recipes to their favorites, and it will sync with database even in the case of accidentally close the window.

2022-05-28 09:28 UTC, DanlandYZ commented
updated most JavaScript files replacing any local storage functions with calls to database. 
Still have linting errors need to be fixed during weekends, 
will double check js files during weekends too.

2022-05-28 19:13 UTC, gmihir requested changes
This is awesome! I found one issue though: when a user favorites a recipe (logged in) and then navigates to the my account page, the favorited recipe does not show up.

2022-05-28 19:23 UTC, gmihir commented
Additionally, I am having trouble creating a recipe.

Uncaught (in promise) TypeError: Cannot set properties of null (setting '0a2d5a7c-8281-4b0c-9719-7bd85da8861c')
    at createRecipe (utils.js:370:25)
    at async HTMLButtonElement.<anonymous> (createRecipe.js:139:24)

2022-06-01 10:01 UTC, DanlandYZ commented
Pretty much all done.

2022-06-05 05:15 UTC, gmihir approved these changes
this is good to go! of course we will need to add some unit tests before release

2022-06-05 05:20 UTC, lramos0 commented on testing/unit/utilsTesting.test.js
> -test('assert readRecipe() returns correct recipe', async () => {
Unit tests broken as a result of implementing CRUD related operations for firebase, expected and known. To be fixed before release.

2022-06-05 05:21 UTC, lramos0 approved these changes
Approving for the sake of unblocking personalization related features. We still have a insufficient unit test suite.

2022-06-06 01:07 UTC, lramos0 commented
I hate testing... but here ya go, have fun!

2022-06-07 02:02 UTC, DanlandYZ commented
this is really wired, the test run locally and test run github are failing different tests
Tests running on github are giving 2, 3, or 4 number of failing tests. 
not really sure what is going on.

2022-06-07 16:57 UTC, ahthai2468 approved these changes
I believe e2e is in a solid position for merging now - of course, we will need new unit testing.

2022-06-07 19:12 UTC, gmihir commented
> I believe e2e is in a solid position for merging now - of course, we will need new unit testing.

ok thanks! i want to merge everything else in first bc this will probably cause a few conflicts

2022-06-07 19:15 UTC, ahthai2468 commented
> > I believe e2e is in a solid position for merging now - of course, we will need new unit testing.
> 
> ok thanks! i want to merge everything else in first bc this will probably cause a few conflicts

Sounds good, I am a bit concerned about unit testing for this. Are we doing unit testing after merging this or before? Will we have the bandwidth to have any semblance of unit testing for this lol

2022-06-08 00:44 UTC, merged